const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const source=fs.readFileSync(require.resolve("../dashboard/app.js"),"utf8");
const storage={getItem:()=>null};
const elements=new Map();
const context={window:{HSFM_FOOD_SCOPE:require("../dashboard/food_scope.js")},sessionStorage:storage,localStorage:storage,document:{addEventListener:()=>{},querySelectorAll:()=>[],querySelector:s=>{if(!elements.has(s))elements.set(s,{value:"",checked:false});return elements.get(s);}}};
vm.createContext(context);
vm.runInContext(source.replace(/  bind\(\);\s+setPerfRange\("yesterday"\);\s+loadData\(\);/,"globalThis.app={state,findReviewItem,getReviewItems,overlayRow,renderDay,invalidateDerived,expandForProducts};"),context);
const {app}=context;
app.state.rows=[{hsshow_id:"mixed",raw_title:"히트상품 앵콜방송4부",source_category:"생활/건강",platform_name:"NS홈쇼핑"}];
assert.equal(app.findReviewItem("히트상품 앵콜방송4부","source_nonfood")?.occurrences[0].hsshow_id,"mixed");
assert.equal(app.getReviewItems("pending").length,0);
app.state.masterPublic=[{match_keyword:"히트상품 앵콜방송4부",standard_product_name:"잘못된 상품",enabled:"Y"}];
app.invalidateDerived();
assert.equal(app.overlayRow({...app.state.rows[0],dynamic_title:"Y",standard_product_name:"잘못된 상품"}).standard_product_name,"");
app.state.adminMaster={occurrence_splits:[{hsshow_id:"mixed",standard_product_name:"마사지건",include_in_food:"N",sales_amt:"8730000"},{hsshow_id:"mixed",standard_product_name:"LA갈비",include_in_food:"Y",sales_amt:"16860000"}]};
app.invalidateDerived();
const mixed=app.overlayRow({...app.state.rows[0],brand:"잘못된 브랜드",sales_amt:25590000});
assert.equal(mixed.sales_amt,16860000);
assert.equal(app.expandForProducts([mixed])[0].brand,"");
app.state.cursor=new Date(2026,8,6);
app.state.rows=[{hsshow_id:"food",broadcast_date:"2026-09-06",start_datetime:"2026-09-06T04:00:00+09:00",raw_title:"LA갈비",source_category:"식품",platform_name:"NS홈쇼핑",sales_amt:16860000,performance_status:"captured"}];
app.state.dayGridHiddenChannels=new Set(["NS홈쇼핑"]);
app.invalidateDerived();
app.renderDay();
assert.match(elements.get("#calendarRoot").innerHTML,/방송 0회/);
assert.match(elements.get("#calendarRoot").innerHTML,/매출 0만원/);
console.log("review_scope tests passed");
